### ISSUE TITLE
Tests hang

### ISSUE THREAD

**Issue by yurivict** [cp2k/dbcsr#72] opened 2018-10-31 21:21 UTC
It stays this way forever:
```
Running tests...
/usr/local/bin/ctest --force-new-ctest-process 
Test project /usr/ports/math/dbcsr/work/.build
      Start  1: dbcsr_perf:inputs/test_rect1_dense.perf
```

FreeBSD 11.2 amd64

**Comment by dev-zero** [comment] 2018-11-01 06:39
possibly a duplicate of #51 

Can you please report: compiler and MPI versions and possibly try to attach a debugger to the hanging process to see where it hangs?

**Comment by alazzaro** [comment] 2018-11-09 13:43
@yurivict could you give us more info on how to reproduce this problem? We don't see this problem in any of our tests. Besides the internal tests, now DBCSR is executed by CP2K (see https://github.com/cp2k/cp2k/pull/86 ) which gives a better coverage of the code, although we don't use FreeBSD...

**Closed** 2018-11-11 17:56 UTC
Labels: can't reproduce
