### ISSUE TITLE
Breaks with gcc-10: Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)

### ISSUE THREAD

**Issue by yurivict** [cp2k/dbcsr#387] opened 2020-11-15 20:32 UTC
```
--- src/CMakeFiles/dbcsr.dir/mpi/dbcsr_mpiwrap.F.o ---
/usr/ports/math/dbcsr/work/.build/src/mpi/dbcsr_mpiwrap.F:21593:44:

21593 |       CALL MPI_FILE_READ_AT_ALL(fh, offset, msg, msg_len, MPI_COMPLEX, MPI_STATUS_IGNORE, ierr)
      |                                            1
......
21615 |       CALL MPI_FILE_READ_AT_ALL(fh, offset, msg, 1, MPI_COMPLEX, MPI_STATUS_IGNORE, ierr)
      |                                            2
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/usr/ports/math/dbcsr/work/.build/src/mpi/dbcsr_mpiwrap.F:21541:40:

21541 |       CALL MPI_FILE_READ_AT(fh, offset, msg, msg_len, MPI_COMPLEX, MPI_STATUS_IGNORE, ierr)
      |                                        1
......
```

Version: 2.0.1
OS: FreeBSD 12.2

**Comment by dev-zero** [comment] 2020-11-16 09:18
which version of DBCSR Is this?

**Comment by dev-zero** [comment] 2020-11-24 07:38
hence a duplicate of #377

**Closed by dev-zero** 2020-11-24 07:38 UTC
Labels: duplicate
